services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
